name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Publish test results
        uses: qase/publish-test-results-action@v2
        with:
            token: ${{6e723270fab0764cd644221166d87114690ec9a2b6f832fdc3d28968c0c118fc}}
            project-code: ACCOUNTS
            run-name: SMOKE
            run-description: SMOKE
            results-path: target/surefire-reports

      - name: Attach Bug screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: screenshots







